### ISSUE TITLE
Using Airflow from dependencies for other purposes : KubernetesPodOperator not available

### ISSUE THREAD

**Issue by Startouf** [open-metadata/openmetadata-helm-charts#113]
Hi, I'm trying to reuse the underlying airflow instance for other purposes and adding new DAGs in the mounted DAG folder.

However, I cannot seem to run the KubernetesPodOperator and my DAGs cannot be imported.

When I use the airflow.contrib one
`from airflow.contrib.operators.kubernetes_pod_operator import KubernetesPodOperator`

I get

```
# log
Broken DAG: [/airflow-dags/dags/dbt.py] Traceback (most recent call last):
  File "/airflow-dags/dags/dbt.py", line 3, in <module>
    from airflow.contrib.operators.kubernetes_pod_operator import KubernetesPodOperator
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/contrib/operators/kubernetes_pod_operator.py", line 25, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes'
```

When I use the airflow.providers one 

```
from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
```

I get

```
from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
```

I'm surprised the jobs from OMD can actually run and spawn new kubernetes workers/jobs without having this dependency. When looking at the deployed code, the airflow image of the pods seem to use your custom docker image `docker.getcollate.io/openmetadata/ingestion:0.13.2`.  Could the kubernetesPodOperator be integrated into this one, or maybe have a different docker image more suited for kubernetes ?

The airflow setup represents several GBs of pod memory, so I'm not keen into duplicating Airflow instances and having just one for OMD, and just one for the rest. I'd rather reuse the one from your OMD-dependencies helm chart which is already connected to OMD. But I'm open to other suggestions

Slack [discussion there](https://openmetadata.slack.com/archives/C02B6955S4S/p1676631154055399)

**Comment by akash-jain-10** [comment]
Hello @Startouf . Adding more notes and references for the above conversation here. 

The Docker Image `docker.getcollate.io/openmetadata/ingestion:0.13.2` is created from Dockerfile available [here](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/Dockerfile).

If you inspect the dockerfile, We are removing the bloated Airflow Installations of providers [here](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/Dockerfile#L78). This means that Ingestion Docker Image is designed to be used with OpenMetadata only. 

However, for your use case, you can always extend the Docker Image and add the dependencies required! Let us know if this helps you going along further! Thanks.

**Comment by Startouf** [comment]
Thanks for the feedback, I believe I have enough information to continue.
