### ISSUE TITLE
YARML parse error when airflow is enabled.

### ISSUE THREAD

**Issue by uprush** [open-metadata/openmetadata-helm-charts#13]
After enabling airflow in values.yaml, I got the following error:
```
vi values.yaml

  airflow:
    enabled: true
```

```
helm install -f values.yaml

Error: UPGRADE FAILED: YAML parse error on openmetadata/templates/deployment.yaml: error converting YAML to JSON: yaml: line 83: block sequence entries are not allowed in this context
```

Looks like a template error in [deployment.yaml](https://github.com/open-metadata/openmetadata-helm-charts/blob/main/charts/openmetadata/templates/deployment.yaml#L95).

**Comment by advincze** [comment]
you need to remove one of the `-`-s from `{{- if .Values.global.airflow.enabled -}}`
