### ISSUE TITLE
MySQL startup probe fails

### ISSUE THREAD

**Issue by OneCyrus** [open-metadata/openmetadata-helm-charts#157]
the mysql pod gets restarted due to the startup probe failure. after disabling the liveness probe it started to work. 

`Startup probe failed: mysqladmin: [Warning] Using a password on the command line interface can be insecure. mysqladmin: connect to server at 'localhost' failed error: 'Can't connect to local MySQL server through socket '/opt/bitnami/mysql/tmp/mysql.sock' (2)' Check that mysqld is running and that the socket: '/opt/bitnami/mysql/tmp/mysql.sock' exists!`

helm value
```
mysql:
  image:
    debug: true
  startupProbe:
    enabled: false
```
debug didn't show any error

**Comment by akash-jain-10** [comment]
Hello @OneCyrus  - Is this still happening ?

**Comment by OneCyrus** [comment]
@akash-jain-10 yes, still same issue

![image](https://github.com/open-metadata/openmetadata-helm-charts/assets/7747800/5dd5124d-01b4-409c-ace8-e271b8a2bc93)

**Comment by apshoemaker** [comment]
We are experiencing this issue, as well.  Any resolution?

**Comment by derik-roby** [comment]
Has anyone found a workaround for this ?

**Comment by elguero6** [comment]
increase startup probe time helped for me

**Comment by akash-jain-10** [comment]
Thanks! Closing this issue here!
