### ISSUE TITLE
Airflow log cleanup not possible when using persistency

### ISSUE THREAD

**Issue by cberge908** [open-metadata/openmetadata-helm-charts#165]
Hi,

we're currently evaluating Open-Metadata and found some interesting gap (or perhaps a feature 🙂) in the openmetadata-dependencies chart: Whenever you have persistency for the Airflow logs enabled, you can't enable the log cleanup (scheduler.logCleanup.enabled). You get a printout by helm when trying to do so:

```sh
$ helm upgrade openmetadata-dependencies open-metadata/openmetadata-dependencies -n open-metadata -f helm_values_openemedata-dependencies_new.yaml
Error: UPGRADE FAILED: execution error at (openmetadata-dependencies/charts/airflow/templates/_helpers/validate-values.tpl:77:5): If `logs.persistence.enabled=true`, then `scheduler.logCleanup.enabled` must be `false`!
```

 Is there a specific reason why it's implemented like this? From my point of view it might make sense to add an option to set the retention period for the logs before they are deleted automatically. For sure we could also simply disable the log persistency at all, but then all logs are lost whenever the pod is being restarted or killed (for whatever reason).

Cheers,
@cberge908

**Comment by akash-jain-10** [comment]
Hello @cberge908 . I believe this might be a good issue candidate for the c[ommunity airflow helm charts](https://github.com/airflow-helm/charts/tree/main/charts/airflow) we are packaging as dependency!

Perhaps this [document](https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/monitoring/log-cleanup.md) might be the right answer for your above scenario!

Let us know if this helps! Cheers.

**Comment by cberge908** [comment]
Thanks for the link @akash-jain-10!
That perfectly explains why the combination is not possible. Will keep an eye on this - issue can be closed from my point of view.
