### ISSUE TITLE
Support InitContainers and side car containers on the deployment 

### ISSUE THREAD

**Issue by lihan** [open-metadata/openmetadata-helm-charts#17]
## Purpose

MySQL uses `jks` as the SSL certificate which is a binary file. Our environment doesn't work with binary file in the configuration manager, only works with text format.

## Proposals

* Support to customise the initContainer, the standard practice here is to use initContainer to convert text certificate into jks and then volume mount into the shared volume with the main container. [See one example here](https://github.com/helm/charts/blob/master/stable/kibana/ci/initcontainers-values.yaml)
* Support side car container.We could run a side car container to act as auth proxy which handles all the SSL connectivity. The MySQL config from openmetadata could use `127.0.0.1` as the mysql server config

The proposed solution does not complicate the general setup, but gives flexibilities to setup in a more security restricted environment.

**Comment by harshach** [comment]
@akash-jain-10 can we add this. I am not able to reproduce the issue with regular mysql that @lihan is facing. 
To unblock them its better to add a side-car option
