### ISSUE TITLE
Add customisation parameter to command and args

### ISSUE THREAD

**Issue by lihan** [open-metadata/openmetadata-helm-charts#18]
We would like to able to customise the startup script in the prod environment.
In the future, we need our own bash script to start the service.

This customisation allows us to continue using offical image while maintain some flexibilities to add audit functionalities to the setup.

With the default value to be same as it is now, it will not impact the normal setup.

```
image: "openmetadata/server:0.8.0"
imagePullPolicy: Always
command: # Customise this command
args:  # And this
```

**Comment by akash-jain-10** [comment]
Hello @lihan . This should not be required anymore after fix from #20 . Let me know if we can close this issue once you test out the changes!
