### ISSUE TITLE
Docker Image No Such Host for docker.getcollate.io

### ISSUE THREAD

**Issue by preetsindhal** [open-metadata/openmetadata-helm-charts#187]
the image repository is mentioned as `docker.getcollate.io/openmetadata/server` but there no such host so insted i have used `docker pull openmetadata/server:1.1.7`

**Comment by tutte** [comment]
@preetsindhal  `docker.getcollate.io/openmetadata/server` is correct. Check you are pulling with the appropiated tag version or have a network issue.
![image](https://github.com/open-metadata/openmetadata-helm-charts/assets/2269035/e654da9c-cce7-4d96-a0eb-48f585513206)
