### ISSUE TITLE
helm install openmetadata open-metadata/openmetadata ERROR on 1.2.3 release

### ISSUE THREAD

**Issue by elguero6** [open-metadata/openmetadata-helm-charts#202]
When I run the command:
helm install openmetadata open-metadata/openmetadata
output:
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: unknown object type "nil" in Secret.data.PIPELINE_SERVICE_CLIENT_HOST_IP

**Comment by preetsshah** [comment]
Hi @elguero6, 
Can you provide the exact steps to reproduce this along with values.yaml if it was modified?

**Comment by elguero6** [comment]
**This fixed it :**

Run:
helm install openmetadata open-metadata/openmetadata --values values.yaml

_Contents of value.yaml:_

openmetadata:
  config:
    pipelineServiceClientConfig:
      hostIp: "localhost"

**Comment by akash-jain-10** [comment]
Thanks. Closing this issue for now!
