### ISSUE TITLE
Using secret to protect database username - openmetadata.config.database.auth.username

### ISSUE THREAD

**Issue by achovelon** [open-metadata/openmetadata-helm-charts#206]
Hello,
The chart is currently protecting database password using secret on these 2 propreties :

```
openmetadata.config.database.auth.password.secretRef
openmetadata.config.database.auth.password.secretKey
```

but there is no possibility to use secret for database username :

`openmetadata.config.database.auth.username`

Do you think we could implement something similar to share the same secret for username and password please ?
Thanks for your help.

**Comment by akash-jain-10** [comment]
Hello @achovelon .

This is not available out of the box though!

One such alternative is to disable database field from Helm Values and pass in the alternative Environments from the Secrets using helm values `envFrom`.

That way, you are in complete control over the database credentials which can be managed and maintained by you without upgrading helm charts values!

Example, you can do something like below with your helm values -

```yaml
openmetadata:
  config:
    ...
    database:
      enabled: false
...
envFrom:
  - secretRef:
       name: openmetadata-db-config
...
```

In the above case, you will responsible to populate all the Environment variables required as database values for Application Configurations. You can view the corresponding environment variable for helm values in the docs [here](https://docs.open-metadata.org/v1.3.x/deployment/kubernetes/helm-values)
![image](https://github.com/open-metadata/openmetadata-helm-charts/assets/15995028/9fb608e6-be0a-4ad8-b70f-ec84c1bea8f8)


I will close this issue the above concluded alternative for you to test out! Thanks.
