### ISSUE TITLE
Error when installing helm chart

### ISSUE THREAD

**Issue by matthew-foreman** [open-metadata/openmetadata-helm-charts#219]
### Checks

- [X] I have checked for existing issues.
- [X] This report is about the Openmetadata Helm Chart.
- [ ] This report is about the Openmetadata Dependencies Helm Chart.

### Description

**Affected module**
Helm chart

**Describe the bug**
When importing the helm chart, I get this error: Error: template: openmetadata/templates/secrets.yaml:24:22: executing "openmetadata/templates/secrets.yaml" at \<b64enc\>: invalid value; expected string. It was working the other day, but stopped working yesterday. I am providing a string. It looks like the value that is having issues is openmetadata.database.host. Chart and App version should be current, but I don't get any output from helm list and can't find it anywhere.

### Steps to reproduce

database host with a string

### Chart Version

X.X.X

### App Version

X.X.X

### Kubernetes Version

v1.28.5-eks-5e0fdde

### Helm Version

v3.14.0

### Have you joined Openmetadata Slack community?

No

**Comment by akash-jain-10** [comment]
Hello @matthew-foreman , What is the format of Database Host you are passing ? Also, it would be good to know OpenMetadata Helm Chart Version here. You can find it using the command `helm search repo open-metadata` (Ref - [docs](https://helm.sh/docs/helm/helm_search_repo/)).

Also, 

> Error: template: openmetadata/templates/secrets.yaml:24:22: executing "openmetadata/templates/secrets.yaml" at <b64enc>: invalid value; expected string

This seems to be more generic issue so not sure if this is related to Database Host. Can you share the manifest generated using the command `helm template <NAME> <CHART> --values <custom-yaml-values>` (ref - [docs](https://helm.sh/docs/helm/helm_template/)). Please redact any confidential data before sharing it! Thanks.

**Comment by akash-jain-10** [comment]
Closing this issue. Feel free to followup by joining our [Slack channel](https://slack-open-metadata.org/) for further queries!
