### ISSUE TITLE
fix pod disruption budget

### ISSUE THREAD

**Issue by aakashg7** [open-metadata/openmetadata-helm-charts#221]
### Checks

- [X] I have checked for existing issues.
- [X] This report is about the Openmetadata Helm Chart.
- [ ] This report is about the Openmetadata Dependencies Helm Chart.

### Description

pod disruption budget can only have either maxUnavailable or minAvailable because minAvailable and maxUnavailable are mutually exclusive, it's basically in the [K8s docs](https://kubernetes.io/docs/tasks/run-application/configure-pdb/)

### Steps to reproduce

just enable podDisruptionBudget in helm values file and you will see the error

### Chart Version

1.3.1

### App Version

1.3.1

### Kubernetes Version

1.25

### Helm Version

3.12.0

### Relevant Logs

```shell
Failed sync attempt to: one or more objects failed to apply, reason: PodDisruptionBudget.policy "openmetadata-poddisruptionbudget" is invalid: spec: Invalid value: policy.PodDisruptionBudgetSpec{MinAvailable:(*intstr.IntOrString)(0xc046c6f5e0), Selector:(*v1.LabelSelector)(0xc046c6f600), MaxUnavailable:(*intstr.IntOrString)(0xc046c6f5c0)}: minAvailable and maxUnavailable cannot be both set .
```

### Custom Helm Values

```yaml
podDisruptionBudget:
    enabled: true
    config:
      maxUnavailable: "1"
      minAvailable: "1"
```

### Have you joined Openmetadata Slack community?

Yes

**Comment by akash-jain-10** [comment]
Hey @aakashg7  - Thanks for raising this issue. Would you like to contribute here ?

**Comment by akash-jain-10** [comment]
Hey @aakashg7  - As per the official documentation of Kubernetes PodDisruptionBudget, `minAvailable` and `maxUnavailable` values are mutually exclusive!

> You can specify only one of maxUnavailable and minAvailable in a single PodDisruptionBudget.

Ref - https://kubernetes.io/docs/tasks/run-application/configure-pdb/

Closing this issue!
