### ISSUE TITLE
Add deployment annotations

### ISSUE THREAD

**Issue by tutte** [open-metadata/openmetadata-helm-charts#223]
### Checks

- [X] I have checked for existing issues.
- [X] This request is about the Openmetadata Helm Chart.
- [ ] This request is about the Openmetadata Dependencies Helm Chart.

### Description

We need to allow a user to add annotations to the OM deployment.
Currently there is support for pod annotations in the template but not for the deployment itself.

### Proposed Implementation

Add a new `deploymentAnnotations` field in `values.yaml` like we have for `podAnnotations`

### Have you joined Openmetadata Slack community?

Yes

**Comment by safayavatsal** [comment]
Done the required changes and created a PR - https://github.com/open-metadata/openmetadata-helm-charts/pull/280#issue-2682633440
