### ISSUE TITLE
Properties not defined in the json schema

### ISSUE THREAD

**Issue by marcelobartsch** [open-metadata/openmetadata-helm-charts#225]
### Checks

- [X] I have checked for existing issues.
- [X] This report is about the Openmetadata Helm Chart.
- [ ] This report is about the Openmetadata Dependencies Helm Chart.

### Description

trying to set airflow values, fails with error
Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
openmetadata:
- openmetadata.config: Additional property airflow is not allowed

### Steps to reproduce

*  helm repo add openmetadata https://helm.open-metadata.org 
* helm install  metadata openmetadata/openmetadata  --debug --dry-run --version 1.3.1 --set openmetadata.config.airflow.host=localhost

### Chart Version

1.3.1

### App Version

1.3.1

### Kubernetes Version

v1.25.16-eks-508b6b3

### Helm Version

version.BuildInfo{Version:"v3.14.0", GitCommit:"3fc9f4b2638e76f26739cd77c7017139be81d0ea", GitTreeState:"clean", GoVersion:"go1.21.6"}

### Relevant Logs

```shell
✗ helm install  metadata openmetadata/openmetadata  --debug --dry-run --version 1.3.1 --set openmetadata.config.airflow.host=localhost
install.go:214: [debug] Original chart version: "1.3.1"
install.go:231: [debug] CHART PATH: /Users/mbartsch/Library/Caches/helm/repository/openmetadata-1.3.1.tgz

Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
openmetadata:
- openmetadata.config: Additional property airflow is not allowed

helm.go:84: [debug] values don't meet the specifications of the schema(s) in the following chart(s):
openmetadata:
- openmetadata.config: Additional property airflow is not allowed

INSTALLATION FAILED
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:154
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.8.0/command.go:983
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.8.0/command.go:1039
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:267
runtime.goexit
        runtime/asm_arm64.s:1197
```

### Custom Helm Values

```yaml
openmetadata.config.airflow.host=localhost
```

### Have you joined Openmetadata Slack community?

Yes

**Comment by akash-jain-10** [comment]
Hey @marcelobartsch . 

The custom helm values will be `openmetadata.config.pipelineServiceClientConfig.metadataApiEndpoint`.

You can view all the available helm values in the docs [here](https://docs.open-metadata.org/v1.3.x/deployment/kubernetes/helm-values).

`openmetadata.config.airflow.host` is not supported! Closing the issue. Thanks.

**Comment by jcordova-jt** [comment]
> You can view all the available helm values in the docs [here](https://docs.open-metadata.org/v1.3.x/deployment/kubernetes/helm-values).
> 
> `openmetadata.config.airflow.host` is not supported! 

`openmetadata.config.airflow.host` is listed in that doc you referenced FYI
