### ISSUE TITLE
Oauth config 

### ISSUE THREAD

**Issue by advincze** [open-metadata/openmetadata-helm-charts#23]
It would be great to be able to configure [Google SSO](https://docs.open-metadata.org/install/enable-security/google-sso/google-config) via the helm chart

idea:
maybe put the `openmetadata.yaml` config into a configmap so it can be easier templated

**Comment by harshach** [comment]
@advincze does the environment variables work for your needs. Otherwise we can add an alternate option

**Comment by akash-jain-10** [comment]
Hello @advincze. This is included with `0.0.12` Helm Chart Release corresponding to `0.9.0` OpenMetadata release. Do try it and let us know how can we improve on that ! Closing this Issue.
