### ISSUE TITLE
Request for Official Helm Chart Status on ArtifactHub

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/openmetadata-helm-charts#234]
![Image](https://github.com/open-metadata/openmetadata-helm-charts/assets/15995028/cb77e5a5-e908-448c-9a99-44bd2eaf6394)

**Comment by akash-jain-10** [comment]
Ref - https://artifacthub.io/docs/topics/repositories/#official-status

**Comment by tutte** [comment]
Moved to [notion](https://www.notion.so/collate-inc/Request-for-Official-Helm-Chart-Status-on-ArtifactHub-49638c5131064880b5b3fa39a1f912b8?pvs=4)
