### ISSUE TITLE
LDAP truststoreConfigType HostName causes error

### ISSUE THREAD

**Issue by wobu** [open-metadata/openmetadata-helm-charts#267]
### Checks

- [X] I have checked for existing issues.
- [X] This report is about the Openmetadata Helm Chart.
- [ ] This report is about the Openmetadata Dependencies Helm Chart.

### Description

ldapConfiguration.truststoreConfigType: HostName

the secrets.yaml template is referencing a wrong value `.Values.openmetadata.config.authentication.ldapConfiguration.trustStoreConfig.hostNameConfig.acceptableHostNames` instead it should reference `.ldapConfiguration.trustStoreConfig.hostNameConfig.acceptableHostNames` like the other ldapConfiguration values. See

https://github.com/open-metadata/openmetadata-helm-charts/blob/b4bae5e59c39373bb0ad476dec8b9d6d952e914e/charts/openmetadata/templates/secrets.yaml#L279

> Error: template: openmetadata/templates/secrets.yaml:279:51: executing "openmetadata/templates/secrets.yaml" at <.Values.openmetadata.config.authentication.ldapConfiguration.trustStoreConfig.hostNameConfig.acceptableHostNames>: nil pointer evaluating interface {}.openmetadata

### Chart Version

1.5.6

### App Version

1.5.6

### Kubernetes Version

1.30.4

### Helm Version

3.15

### Relevant Logs

```shell
Error: template: openmetadata/templates/secrets.yaml:279:51: executing "openmetadata/templates/secrets.yaml" at <.Values.openmetadata.config.authentication.ldapConfiguration.trustStoreConfig.hostNameConfig.acceptableHostNames>: nil pointer evaluating interface {}.openmetadata
```

### Have you joined Openmetadata Slack community?

Yes

**Comment by tutte** [comment]
Thanks for reporting @wobu . It should be fixed in helm chart `1.5.9` :raised_hands:
