### ISSUE TITLE
MySQL database has a hardcoded password in the initialisation script

### ISSUE THREAD

**Issue by flowy0** [open-metadata/openmetadata-helm-charts#28]
There is a bug where the  MySQL database init script has a hardcoded password.

from [charts/deps/values.yaml](https://github.com/open-metadata/openmetadata-helm-charts/blob/main/charts/deps/values.yaml)
```
initdbScripts:
    init_openmetadata_db_scripts.sql: |
      CREATE DATABASE openmetadata_db;
      CREATE USER 'openmetadata_user'@'%' IDENTIFIED BY 'openmetadata_password';
      GRANT ALL PRIVILEGES ON openmetadata_db.* TO 'openmetadata_user'@'%' WITH GRANT OPTION;
```
In the readme, it mentions to create a password of your choice under the secret `mysql-secrets`

As the init script has a hardcoded value, the Open Metadata Server is unable to connect to MySQL DB on 
deployment.

**Comment by flowy0** [comment]
Have edited the values to use the helm chart options to create a database with the password set from a secret.

```bash
kubectl create secret generic mysql-secrets-new \
  --from-literal=mysql-root-password=mysecret \
  --from-literal=mysql-replication-password=test-pass \
  --from-literal=mysql-password=testing
```

Would suggest that values be changed in this way: 
https://github.com/flowy0/openmetadata-helm-charts/blob/main/charts/deps/values.yaml

**Comment by harshach** [comment]
@flowy0 we did change this to passing parameters and added value support. I am going to close this as fixed. Please re-open if necessary

**Comment by flowy0** [comment]
Just took a look at https://github.com/open-metadata/openmetadata-helm-charts/blob/main/charts/deps/values.yaml, can i check how the mysql password is parameterised?

**Comment by akash-jain-10** [comment]
Hello @flowy0. You can always provide custom values.yaml file to override and configure mysql with helm charts. These are basic parameters set for anyone to get started with ease. We are using mysql helm charts by Bitnami. You can override all the values exposed by the [mysql bitnami helm charts](https://github.com/bitnami/charts/tree/master/bitnami/mysql) under mysql.* for openmetadata/dependencies.

Let me know if this works for you!
