### ISSUE TITLE
Ability to run Post Upgrade Steps for `deploy-pipelines` and `reindex` as Kubernetes CronJob

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/openmetadata-helm-charts#287]
### Checks

- [X] I have checked for existing issues.
- [X] This request is about the Openmetadata Helm Chart.
- [ ] This request is about the Openmetadata Dependencies Helm Chart.

### Description

We need to add Kubernetes CronJobs for running `openmetadata-ops.sh deploy-pipelines` and `openmetadata-ops.sh reindex` as part of Post Upgrade Actions which can be triggered manually / automated with CIs or `kubectl CLI`.

This CronJobs will have ablilty to take additionalArgs required for the `openmetadata-ops.sh` script.

It should be `suspend: true` by default.

With `kubectl`, you can trigger it with `kubectl create job <JOB_NAME> --from=cronjob/<CRON_JOB_NAME> --namespace <NAMESPACE_NAME>`.

### Proposed Implementation

N/A

### Have you joined Openmetadata Slack community?

Yes

**Comment by tarunpandey23** [comment]
Hi @akash-jain-10 
Need your review.

https://github.com/open-metadata/openmetadata-helm-charts/pull/288#issue-2719562283

**Comment by safayavatsal** [comment]
Created the PR - https://github.com/open-metadata/openmetadata-helm-charts/pull/290#issue-2720100269

**Comment by akash-jain-10** [comment]
- [ ] Add Documentation in OpenMetadata Docs for usage
