### ISSUE TITLE
Typo causing possible trouble in key reference

### ISSUE THREAD

**Issue by tkaymak** [open-metadata/openmetadata-helm-charts#29]
https://github.com/open-metadata/openmetadata-helm-charts/blob/51f616c855d145cd2937a220f4a1d69acc8f4f14/charts/openmetadata/values.yaml#L31

Should this be `openmetadata-elasticsearch-password`?

**Comment by akash-jain-10** [comment]
@tkaymak . Thanks that was a good catch! We will publish a new release for the same.
