### ISSUE TITLE
CreateContainerConfigError: secret "airflow-mysql-secrets" not found

### ISSUE THREAD

**Issue by SomniVertix** [open-metadata/openmetadata-helm-charts#46]
## Issue
When installing the default steps, we end up with a few deployments (generated by openmetadata-dependencies) that are stuck failing with the error:

CreateContainerConfigError: secret "airflow-mysql-secrets" not found
![image](https://user-images.githubusercontent.com/35609960/171194820-dc61c757-1aa7-4530-9a05-bd7fedf4f01b.png)

## Steps to reproduce
1. kubectl create secret generic mysql-secrets --from-literal=openmetadata-mysql-password=openmetadata_password
2. kubectl create secret generic airflow-secrets --from-literal=openmetadata-airflow-password=admin
3. helm repo add open-metadata https://helm.open-metadata.org/
4. helm install openmetadata-dependencies open-metadata/openmetadata-dependencies

**Comment by akash-jain-10** [comment]
Hello @SomniVertix ,
Looks like you are missing a step to create `airflow-mysql-secrets` as per documentation [here](https://docs.open-metadata.org/deploy/deploy-on-kubernetes#quickstart). 

`kubectl create secret generic airflow-mysql-secrets --from-literal=airflow-mysql-password=airflow_pass`

![image](https://user-images.githubusercontent.com/15995028/171227545-520c3933-c5d8-4abc-8e34-b168e9dbfd21.png)


Let us know if this helps!
