### ISSUE TITLE
Improve on usage of environment variables with Kubernetes Secrets

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/openmetadata-helm-charts#66]
OpenMetadata currently uses Environment Variables to map values from values.yaml. Improve on this to use Kubernetes Secrets within the Helm Charts for better security.

**Comment by akash-jain-10** [comment]
Will start with `fernetKey`. Currently, we are passing fernetKey using Helm Values as plain string and using that in environment variable directly.

So, the requirement here is that if user passes fernetKey as plain Text, OpenMetadata Helm Chart will convert it into Kubernetes Secrets and mount to deployments and helm hooks as Environment Variable from Kubernetes Secrets (default).

If user has already created Kubernetes Secret for Fernet Key Outside of OpenMetadata Helm Chart, we need to provide helm values to directly use that instead of using the default approach (mentioned above). Similar to how we are passing pre created secrets of [database auth](https://github.com/open-metadata/openmetadata-helm-charts/blob/main/charts/openmetadata/values.yaml#L44-L46).

**Comment by dhruvinmaniar123** [comment]
Thanks Akash. I would like to take this task up.
