### ISSUE TITLE
helm chart documentation for custom OIDC is incorrect

### ISSUE THREAD

**Issue by apshoemaker** [open-metadata/openmetadata-helm-charts#75]
I'm not sure where the best place to report this is, but on [this](https://docs.open-metadata.org/deployment/security/custom-oidc/kubernetes) page of documentation it appears that the`global.airflow.openmetadata.customoidc.secretKeyPath` parameter to set the client secret is inaccurate according to [here](https://github.com/open-metadata/openmetadata-helm-charts/blob/main/charts/openmetadata/templates/_helpers.tpl#L112-L121).  If you will notice, there is the addition of an `.authConfig` group as well as an object called `secretKey` that specifies the `secretRef` and `secretKey` to reference.

I thought perhaps [this](https://github.com/open-metadata/docs) repo would be the place to add a PR correcting the documentation, but I'm not seeing anything in the [content](https://github.com/open-metadata/docs/tree/main/content) directory that leads me to the markdown that I need to edit.

**Comment by harshach** [comment]
@akash-jain-10 can we close this?
