### ISSUE TITLE
Chart can be configured with bitnami/airflow

### ISSUE THREAD

**Issue by mustafa-rmd** [open-metadata/openmetadata-helm-charts#78]
Hey guys,

I am trying to get configure airflow as the main pipeline service for OpenMetaData in my Kubernetes cluster. I am using the official open meta data helm chart along with the airflow managed by bitnami. See chart links section for links.

What have I done:
For bitnami/airflow value.yaml

I installed the python packages as mentioned in the official page: https://docs.open-metadata.org/openmetadata/connectors/pipeline/airflow/lineage-backend

```
openmetadata-ingestion
openmetadata-airflow-managed-apis
```

and set the following environment variables to configure a lineage backend:

```
AIRFLOW__LINEAGE__BACKEND="airflow_provider_openmetadata.lineage.openmetadata.OpenMetadataLineageBackend"
AIRFLOW__LINEAGE__AIRFLOW_SERVICE_NAME="airflow_helm"
AIRFLOW__LINEAGE__OPENMETADATA_API_ENDPOINT="http://openmetadata:8585/api"
AIRFLOW__LINEAGE__AUTH_PROVIDER_TYPE="no-auth"
```

For OpenMetaData I disable the default airflow pod that comes with OpenMetaData and add the configuration for the bitnami/airflow.

Issue:
Now. Going to OpenMetaData UI I getting the following error

`Airflow Exception [Failed to get Pipeline Service host IP.] due to [Failed to get Pipeline Service host IP due to { "detail": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.", "status": 404, "title": "Not Found", "type": "about:blank" } ].
`
	
Basically, OpenMetaData cannot find Airflow. Note, that both in the same namespace which is not the default. I tried debugging for hours and could not found the source of the issue.

Thanks for the help. I attached the values for both OpenMetaData and Bitnami/airflow.

Chart versions links:
Open meta data helm - https://github.com/open-metadata/openmetadata-helm-charts
Airflow helm - https://github.com/bitnami/charts/tree/master/bitnami/airflow

Versions:
Helm version: 3.2.1

[airflow_values.txt](https://github.com/open-metadata/openmetadata-helm-charts/files/9692526/airflow_values.txt)
[openmeta_dep_values.txt](https://github.com/open-metadata/openmetadata-helm-charts/files/9692527/openmeta_dep_values.txt)
[openmeta_values.txt](https://github.com/open-metadata/openmetadata-helm-charts/files/9692528/openmeta_values.txt)

**Comment by akash-jain-10** [comment]
Hello @mustafa-rmd .

A couple of things to verify in this scenario!

> Note, that both in the same namespace which is not the default.

Can you verify once with [openmetada_values.txt](https://github.com/open-metadata/openmetadata-helm-charts/files/9692528/openmeta_values.txt) - the airflow host should be `http://<airflow-web-server-service-name>.<kubernetes-namespace-name>.svc.cluster.local:8080` for` global.airflow.host` ?

Also, can you verify if you are able to hit the openmetadata airflow endpoint (Get Request)`http://<airflow-web-server-service>:8080/api/v1/openmetadata/health` and receive a response ?

**Comment by mustafa-rmd** [comment]
Hey @[akash-jain-10](https://github.com/akash-jain-10) 

I updated the OpenMetaData values 

From: http://airflow:8080/ 
to: http://airflow.{MY_NAMESPACE}.svc.cluster.local:8080

as suggested


as for the health check from airflow to OpenMetaData this is the response I am getting from airflow

```
{
    "detail": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.",
    "status": 404,
    "title": "Not Found",
    "type": "about:blank"
}
```
I attached the error I get from the UI
![Error](https://user-images.githubusercontent.com/112797628/193531026-f4cd0333-4284-4193-886d-d9ee6cfee3dc.JPG)

**Comment by akash-jain-10** [comment]
Hello @mustafa-rmd . Let me create a similar environment on my end and debug things a little further. Meanwhile would request you to join our community [Slack](https://openmetadata.slack.com) to get a quicker conversation around this.

**Comment by mustafa-rmd** [comment]
Hi @akash-jain-10 thanks for the help.

Will definitely join the slack. See below information for more details about the charts version for openmetadata

```
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION
open-metadata/openmetadata              0.0.37          0.12.0          A Helm chart for OpenMetadata on Kubernetes
open-metadata/openmetadata-dependencies 0.0.37          0.12.0          Helm Dependencies for OpenMetadata
```

As for airflow. See details as well

```
NAME            CHART VERSION   APP VERSION     DESCRIPTION
bitnami/airflow 13.1.4          2.3.4           Apache Airflow is a tool to express and execute...
```

**Comment by akash-jain-10** [comment]
Closing this issue. The fix here is to use `openmetadata-managed-apis` Python Package with Bitnami Airflow and as confirmed by you [here](https://openmetadata.slack.com/archives/C02B6955S4S/p1666091873347839) this was the missing part!

**Comment by Armadik** [comment]
@akash-jain-10 I have a similar problem, tell me what version of airflow is used?
  Apparently, while openmetadata-airflow-managed-apis is not suitable for version 2.4.2
