### ISSUE TITLE
Validate OpenMetadata Helm Chart Values specific to OpenMetadata Configurations

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/openmetadata-helm-charts#84]
Below are the list of conditions to handle as part of this Issue:

- [x] `global.authorizer.className` will only have a fixed value of `org.openmetadata.service.security.DefaultAuthorizer`
- [x] `global.authorizer.containerRequestFilter` will only have a fixed value of `org.openmetadata.service.security.JwtFilter`
- [x] `global.secretsManager.provider` can only have values as `noop, aws, aws-ssm`
- [x] ~If `global.airflow.openmetadata.authProvider` value is `azure`, then `global.airflow.openmetadata.authConfig.azure.clientSecret.secretRef`, `global.airflow.openmetadata.authConfig.azure.clientSecret.secretKey`, `global.airflow.openmetadata.authConfig.azure.authority`, `global.airflow.openmetadata.authConfig.azure.clientId` and `global.airflow.openmetadata.authConfig.azure.scopes` field are required~
- [x] ~If `global.airflow.openmetadata.authProvider` value is `google`, then `global.airflow.openmetadata.authConfig.google.secretKeyPath` and `global.airflow.openmetadata.authConfig.google.audience` is required~
- [x] ~If `global.airflow.openmetadata.authProvider` value is `okta`, then `global.airflow.openmetadata.authConfig.okta.privateKey.secretRef`, `global.airflow.openmetadata.authConfig.okta.privateKey.secretKey`, `global.airflow.openmetadata.authConfig.okta.email`, `global.airflow.openmetadata.authConfig.okta.clientId`, `global.airflow.openmetadata.authConfig.okta.orgUrl`, `global.airflow.openmetadata.authConfig.okta.scopes` is required~
- [x] ~If `global.airflow.openmetadata.authProvider` value is `auth0`, then `global.airflow.openmetadata.authConfig.auth0.clientId`, `global.airflow.openmetadata.authConfig.auth0.secretKey.sercretRef`, `global.airflow.openmetadata.authConfig.auth0.secretKey.secretKey`, `global.airflow.openmetadata.authConfig.auth0.domain` is required~
- [x] ~If `global.airflow.openmetadata.authProvider` value is `openmetadata`, then `global.airflow.openmetadata.authConfig.openMetadata.jwtToken.secretRef`, `global.airflow.openmetadata.authConfig.openMetadata.jwtToken.secretKey` is required~
- [x] ~If `global.airflow.openmetadata.authProvider` value is `custom-oidc`, then `global.airflow.openmetadata.authConfig.customOidc.secretKey.secretRef`, `global.airflow.openmetadata.authConfig.customOidc.secretKey.secretKey`, `global.airflow.openmetadata.authConfig.customOidc.clientId`, `global.airflow.openmetadata.authConfig.customOidc.tokenEndpoint` is required~

**Comment by Ashok810** [comment]
assign to this one

**Comment by Ashok810** [comment]
please assign this one

**Comment by mavimo** [comment]
@akash-jain-10 I suppose the condition on `auth0` are always referring to properties in `global.airflow.openmetadata.authConfig.auth0`  and not `okta`, right?

**Comment by harshach** [comment]
@akash-jain-10 what is remaining here?

**Comment by akash-jain-10** [comment]
Hello @harshach . We are waiting for @mavimo to update the PR for the above 4 checklist's.

**Comment by harshach** [comment]
@akash-jain-10 lets take the PR and update ourselves. We don't need to wait for this to keep updated
