### ISSUE TITLE
Readiness probe fails with TLS 

### ISSUE THREAD

**Issue by revit13** [open-metadata/openmetadata-helm-charts#97]
Openemetadata version: `0.0.39`

When configuring Openmetadata with TLS I get the following error:

`Warning  Unhealthy  3m45s (x2822 over 16h)  kubelet  Readiness probe failed: Get "http://10.244.1.16:8585/": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x03\x00\x02\x02P"`

The http check fails as the server is using https

**Comment by akash-jain-10** [comment]
Hello @revit13 . Thanks for filing this issue. We will break this further into 2 issues and provide ability to achieve and fix the above issue.

- [ ] #99
- [ ] #100

Will be tracking all the development work there. Thanks!

**Comment by revit13** [comment]
Hi @akash-jain-10 thanks for the update. another issue related to tls is how to configure the deps chars (airflow for example) with tls. I know its out of openmetadata repo scope but IIUC to run with tls end to end the deps should also use tls. It would be great it an example [value.yaml](https://github.com/open-metadata/openmetadata-helm-charts/blob/main/charts/deps/values.yaml) configured for tls could be added.  Thanks

**Comment by akash-jain-10** [comment]
Hello @revit13 . Our Dependencies Chart is based on other Helm Charts ([MySQL](https://artifacthub.io/packages/helm/bitnami/mysql), [ElasticSearch](https://github.com/elastic/helm-charts), [Airflow-helm](https://github.com/airflow-helm/charts/tree/main/charts/airflow)). Feel free to navigate to their docs and setup the TLS as provided be each helm chart.
